#定义持续集成流程模板,大小写敏感、使用缩进代表层级、不允许使用Tab缩进,只能使用空格
#为了降低服务器的负载,dev分支不触发流水线

#stages表示不同阶段
stages:
    - install_deps
    - build
    - audit
    - test
    - deploy
    - dast



#测试CI
unit:
    stage: test
    script:
    - echo "test unit..."
    except:
    - /_dev$/
    tags:
    - my_runner_2

#自动部署
deploy:
    stage: deploy
    script:
    # export
    - echo $CI_COMMIT_REF_NAME
    - gitlab-ci-deploy $CI_PROJECT_NAMESPACE $CI_PROJECT_NAME $CI_COMMIT_REF_NAME
    - echo $CI_PROJECT_NAMESPACE $CI_PROJECT_NAME $CI_COMMIT_REF_NAME
    except:
    - /_dev$/
    tags:
    - my_runner_3

    
    script:
    - mkdir /zap/wrk/
    - /zap/zap-baseline.py -J gl-dast-report.json -t http://xxx.com || true
    - cp /zap/wrk/gl-dast-report.json .
    
    
  dast:
    stage: dast
    image: registry.gitlab.com/gitlab-org/security-products/zaproxy
    variables:
    website: "http://localhost:8080//blockchain"
    allow_failure: true
    script:
      - mkdir /zap/wrk/ -p
      - /zap/zap-baseline.py -J gl-dast-report.json -t $website || true
      - cp /zap/wrk/gl-dast-report.json .
   
       tags:
    - my_runner_4
      except:
    - /_dev$/